// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANuN152HUzo2IkbyiCK9RQ7yYsNe4Lkjc',
    appId: '1:941622874316:web:c79a3d723db572cdc67269',
    messagingSenderId: '941622874316',
    projectId: 'humanmatch-4ab47',
    authDomain: 'humanmatch-4ab47.firebaseapp.com',
    storageBucket: 'humanmatch-4ab47.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsmsPqMTihTVXj5fV6gOytc8TVzzY95gc',
    appId: '1:941622874316:android:ca506cf7e7ed814ac67269',
    messagingSenderId: '941622874316',
    projectId: 'humanmatch-4ab47',
    storageBucket: 'humanmatch-4ab47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpZ6J6CZblijqsDeAwqX_oQYqG-J4zvAs',
    appId: '1:941622874316:ios:e09c16d11cf6a23ac67269',
    messagingSenderId: '941622874316',
    projectId: 'humanmatch-4ab47',
    storageBucket: 'humanmatch-4ab47.firebasestorage.app',
    iosBundleId: 'com.example.humanMatchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpZ6J6CZblijqsDeAwqX_oQYqG-J4zvAs',
    appId: '1:941622874316:ios:e09c16d11cf6a23ac67269',
    messagingSenderId: '941622874316',
    projectId: 'humanmatch-4ab47',
    storageBucket: 'humanmatch-4ab47.firebasestorage.app',
    iosBundleId: 'com.example.humanMatchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANuN152HUzo2IkbyiCK9RQ7yYsNe4Lkjc',
    appId: '1:941622874316:web:d608f7e3af181152c67269',
    messagingSenderId: '941622874316',
    projectId: 'humanmatch-4ab47',
    authDomain: 'humanmatch-4ab47.firebaseapp.com',
    storageBucket: 'humanmatch-4ab47.firebasestorage.app',
  );
}
