import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';

import '../../l10n/app_localizations.dart';
import '../../calc/numerology.dart';
import '../../hd/human_design_section.dart';
import '../../ai_actions.dart';
import '../../utils/astro_utils.dart';
import '../loading_widget.dart';
import '../widgets/common_ui.dart';
import 'profile_input_screen.dart';

class ProfileSummaryScreen extends StatefulWidget {
  const ProfileSummaryScreen({super.key});
  @override
  State<ProfileSummaryScreen> createState() => _ProfileSummaryScreenState();
}

class _ProfileSummaryScreenState extends State<ProfileSummaryScreen> {
  bool _didAutoDaily = false;
  late AiActions _ai;

  bool _loadingInsights = false;
  bool _loadingTip = false;

  @override
  void initState() {
    super.initState();
    _ai = AiActions(context: context);
    _autoGenerateDailyTip();
  }

  Future<void> _autoGenerateDailyTip() async {
    if (_didAutoDaily) return;
    _didAutoDaily = true;
    if (mounted) setState(() => _loadingTip = true);
    try {
      final callable = FirebaseFunctions.instance.httpsCallable('generateDailyTipIfNeeded');
      await callable.call({
        'dateKey': _ai.todayKeyLocal(),
        'language': _ai.getLanguageCode(),
      });
    } catch (_) {} finally {
      if (mounted) setState(() => _loadingTip = false);
    }
  }

  String _firstName(String fullName) {
    final parts = fullName.trim().split(RegExp(r'\s+'));
    return parts.isEmpty ? '' : parts.first;
  }

  String _formatDateStr(String? key, String defaultTitle) {
    if (key == null || !key.contains('-')) return defaultTitle;
    final parts = key.split('-');
    if (parts.length != 3) return key;
    return '${parts[2]}-${parts[1]}-${parts[0]}';
  }

  @override
  Widget build(BuildContext context) {
    final user = FirebaseAuth.instance.currentUser!;
    final userRef = FirebaseFirestore.instance.collection('users').doc(user.uid);
    final insightsRef = userRef.collection('aiInsights').doc('latest');
    final lastTipQuery = userRef.collection('dailyTips').orderBy('dateKey', descending: true).limit(1);
    final l10n = AppLocalizations.of(context)!;

    return StreamBuilder<DocumentSnapshot<Map<String, dynamic>>>(
      stream: userRef.snapshots(),
      builder: (context, userSnap) {
        if (userSnap.connectionState == ConnectionState.waiting && !userSnap.hasData) {
          return const Center(child: LoadingWidget());
        }

        final u = userSnap.data?.data() ?? {};
        final fullName = (u['name'] ?? '').toString().trim();
        final first = _firstName(fullName);
        final birthDateStr = (u['birthDateStr'] ?? '').toString();
        final birthTimeStr = (u['birthTimeStr'] ?? '').toString();
        final birthDateText = [birthDateStr, birthTimeStr].where((s) => s.trim().isNotEmpty).join(' • ');
        final placeLabel = (u['birthPlaceLabel'] ?? (u['place'] as Map?)?['label'] ?? '').toString();

        final hdBase = (u['humanDesignBase'] as Map?)?.cast<String, dynamic>();
        final astro = (u['astro'] as Map?)?.cast<String, dynamic>() ?? {};

        final sunSign = astro['sunSign'] ?? (findBodyLongitude(hdBase, true, 'Sun') != null ? getZodiacSign(context, findBodyLongitude(hdBase, true, 'Sun')!) : '—');
        final ascSign = astro['ascendantSign'] ?? (astro['ascendantDeg'] != null ? getZodiacSign(context, (astro['ascendantDeg'] as num).toDouble()) : '—');

        final storedNum = u['numerology'] as Map?;
        final numerology = storedNum != null ? NumerologyResult(lifePath: storedNum['lifePath'], expression: storedNum['expression'], soul: storedNum['soul'], personality: storedNum['personality']) : null;

        return ListView(
          key: const PageStorageKey('profile_summary_list'),
          children: [
            PrimaryCard(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      const CircleAvatar(
                        radius: 22,
                        backgroundColor: Colors.transparent,
                        child: Image(image: AssetImage('assets/icon/card.png')),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Text(
                          first.isEmpty ? l10n.greetingEmpty : l10n.greeting(first),
                          style: const TextStyle(fontSize: 22, fontWeight: FontWeight.w900),
                        ),
                      ),
                      IconButton(
                        tooltip: l10n.update,
                        onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => const ProfileInputScreen())),
                        icon: const Icon(Icons.edit_outlined),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      if (birthDateText.isNotEmpty)
                        Expanded(child: InfoRow(icon: Icons.cake_outlined, label: l10n.birthDate, value: birthDateText)),
                      if (birthDateText.isNotEmpty && placeLabel.isNotEmpty) const SizedBox(width: 12),
                      if (placeLabel.isNotEmpty)
                        Expanded(child: InfoRow(icon: Icons.place_outlined, label: l10n.birthPlace, value: placeLabel, isRightAligned: true)),
                    ],
                  ),
                ],
              ),
            ),
            const SizedBox(height: 12),
            PrimaryCard(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(l10n.hdTitle, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w900)),
                  const SizedBox(height: 12),
                  if (hdBase == null) Text(l10n.hdCalculating) else HumanDesignSection(hd: hdBase),
                ],
              ),
            ),
            const SizedBox(height: 12),
            PrimaryCard(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(l10n.astroTitle, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w900)),
                  const SizedBox(height: 12),
                  Card(
                    elevation: 0,
                    child: Padding(
                      padding: const EdgeInsets.all(12),
                      child: Column(
                        children: [
                          KeyValueRow(icon: Icons.wb_sunny_outlined, label: l10n.zodiacSign, value: sunSign),
                          const SizedBox(height: 10),
                          KeyValueRow(icon: Icons.north_outlined, label: l10n.ascendant, value: ascSign),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 12),
            PrimaryCard(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(l10n.numTitle, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w900)),
                  const SizedBox(height: 12),
                  if (numerology == null) const Text('—') else
                    Card(
                      elevation: 0,
                      child: Padding(
                        padding: const EdgeInsets.all(12),
                        child: Column(
                          children: [
                            KeyValueRow(icon: Icons.tag_outlined, label: l10n.lifePath, value: numerology.lifePath.toString()),
                            const SizedBox(height: 10),
                            KeyValueRow(icon: Icons.tag_outlined, label: l10n.expression, value: numerology.expression.toString()),
                            const SizedBox(height: 10),
                            KeyValueRow(icon: Icons.tag_outlined, label: l10n.soul, value: numerology.soul.toString()),
                            const SizedBox(height: 10),
                            KeyValueRow(icon: Icons.tag_outlined, label: l10n.personality, value: numerology.personality.toString()),
                          ],
                        ),
                      ),
                    ),
                ],
              ),
            ),
            const SizedBox(height: 12),
            StreamBuilder<DocumentSnapshot<Map<String, dynamic>>>(
              stream: insightsRef.snapshots(),
              builder: (context, insSnap) {
                final isLoading = _loadingInsights || (insSnap.connectionState == ConnectionState.waiting && !insSnap.hasData);
                final ins = insSnap.data?.data();
                final exists = insSnap.data?.exists ?? false;

                Widget inner;
                if (!exists) {
                  inner = Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(l10n.profileInsights, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w900)),
                      const SizedBox(height: 10),
                      Text(l10n.noInsights),
                      const SizedBox(height: 12),
                      ElevatedButton(
                        onPressed: isLoading ? null : () async {
                          setState(() => _loadingInsights = true);
                          await _ai.runInsightsBehindRewardedAd();
                          if (mounted) setState(() => _loadingInsights = false);
                        },
                        child: Text(l10n.generateInsights),
                      ),
                    ],
                  );
                } else {
                  final data = ins ?? {};
                  inner = Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          Expanded(child: Text(l10n.profileInsights, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w900))),
                          TextButton.icon(
                            onPressed: isLoading ? null : () async {
                              setState(() => _loadingInsights = true);
                              await _ai.runInsightsBehindRewardedAd();
                              if (mounted) setState(() => _loadingInsights = false);
                            },
                            icon: const Icon(Icons.auto_awesome_outlined),
                            label: Text(l10n.update),
                          ),
                        ],
                      ),
                      const SizedBox(height: 10),
                      Text(data['summary']?.toString() ?? '—'),
                      const SizedBox(height: 12),
                      Text(l10n.profilePillars, style: const TextStyle(fontWeight: FontWeight.w900)),
                      _bullets(data['insights'] ?? []),
                    ],
                  );
                }

                return PrimaryCard(
                  child: Stack(
                    alignment: Alignment.center,
                    children: [
                      Opacity(opacity: isLoading ? 0.4 : 1.0, child: inner),
                      if (isLoading) const LoadingWidget(),
                    ],
                  ),
                );
              },
            ),
            const SizedBox(height: 12),
            StreamBuilder<QuerySnapshot<Map<String, dynamic>>>(
              stream: lastTipQuery.snapshots(),
              builder: (context, tipsSnap) {
                final isLoading = _loadingTip || (tipsSnap.connectionState == ConnectionState.waiting && !tipsSnap.hasData);

                final tips = tipsSnap.data?.docs ?? [];
                final hasTodayTip = tips.isNotEmpty && tips.first.id == _ai.todayKeyLocal();
                final lastTipDoc = tips.isNotEmpty ? tips.first : null;
                final lastTipData = lastTipDoc?.data() ?? {};

                final formattedDate = lastTipDoc != null
                    ? _formatDateStr(lastTipDoc.id, l10n.dailyTip)
                    : _formatDateStr(_ai.todayKeyLocal(), l10n.dailyTip);

                final inner = Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(l10n.dailyTip, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w900)),
                    const SizedBox(height: 10),
                    Text(formattedDate, style: const TextStyle(fontWeight: FontWeight.w900)),
                    const SizedBox(height: 8),

                    if (!hasTodayTip) ...[
                      ElevatedButton.icon(
                        onPressed: isLoading ? null : () async {
                          setState(() => _loadingTip = true);
                          await _ai.runTipsBehindRewardedAd();
                          if (mounted) setState(() => _loadingTip = false);
                        },
                        icon: const Icon(Icons.auto_awesome_outlined),
                        label: Text(l10n.getDailyTip),
                      ),
                      const SizedBox(height: 14),
                    ],

                    if (lastTipDoc != null)
                      Text(lastTipData['text']?.toString() ?? '—')
                    else
                      Text(l10n.watchAdForTip),
                  ],
                );

                return PrimaryCard(
                  child: Stack(
                    alignment: Alignment.center,
                    children: [
                      Opacity(opacity: isLoading ? 0.4 : 1.0, child: inner),
                      if (isLoading) const LoadingWidget(),
                    ],
                  ),
                );
              },
            ),
          ],
        );
      },
    );
  }

  Widget _bullets(List items) {
    if (items.isEmpty) return const Text('—');
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: items.map((t) => Padding(padding: const EdgeInsets.symmetric(vertical: 4), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('• '), Expanded(child: Text(t.toString()))]))).toList(),
    );
  }
}
